steps:
  - name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - >
        docker build
        --build-arg OPENAI_API_KEY=$$OPENAI_API_KEY
        --build-arg TAVILY_API_KEY=$$TAVILY_API_KEY
        --build-arg GEMINI_API_KEY=$$GEMINI_API_KEY
        -t $_IMAGE
        .
    secretEnv:
      - OPENAI_API_KEY
      - TAVILY_API_KEY
      - GEMINI_API_KEY

  - name: gcr.io/cloud-builders/docker
    args: ["push", "$_IMAGE"]

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args:
      - run
      - deploy
      - $_SERVICE
      - --image=$_IMAGE
      - --region=$_REGION
      - --platform=managed
      - --allow-unauthenticated
      - --port=8080

substitutions:
  _REGION: us-central1
  _SERVICE: costli2
  _IMAGE: us-central1-docker.pkg.dev/$PROJECT_ID/costli-repo/costli2:latest

images:
  - $_IMAGE

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/OPENAI_API_KEY/versions/latest
      env: OPENAI_API_KEY
    - versionName: projects/$PROJECT_ID/secrets/TAVILY_API_KEY/versions/latest
      env: TAVILY_API_KEY
    - versionName: projects/$PROJECT_ID/secrets/GEMINI_API_KEY/versions/latest
      env: GEMINI_API_KEY
